version: '3'

volumes:
  kittygram_pg_volume:
  static_volume:

services:
  postgres_db:
    image: postgres:13
    env_file: .env
    volumes: 
      - kittygram_pg_volume:/var/lib/postgresql/data/
  backend:
    depends_on:
      - postgres_db
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static/
  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - static_volume:/static
    command: cp -r /app/build/. /static/
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
