name: Kittygram Workflow (main)

on:
  push:
    branches:
      - main

jobs:

  backend_tests:
    name: Run tests for backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Clone Kittygram to runner
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0
          pip install flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt
      - name: Run flake8 tests
        run: python -m flake8 backend/
      - name: Run Django tests
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          cd backend/
          python manage.py test

  build_and_push_backend_image:
    name: Build backend image and push to the DockerHub
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Clone Kittygram to runner
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push backend image to the Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: True
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest

  send_message_telegram:
    name: Send message to telegram
    runs-on: ubuntu-latest
    needs: build_and_push_backend_image
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Деплой "Kittygram" выполнен успешно!
