name: Kittygram Workflow (main)

on:
  push:
    branches:
      - main

jobs:

  backend_tests:
    name: Run tests for backend
    runs-on: ubuntu-latest
    steps:
      - name: Clone Kittygram to runner
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0
          pip install flake8-isort==6.0.0
      - name: Run flake8 tests
        run: python -m flake8 backend/

  send_message_telegram:
    name: Send message to telegram
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Деплой "Kittygram" выполнен успешно!